blastn -query atp1.fasta -db watermelon.fsa
blastn -query atp4.fasta -db watermelon.fsa
blastn -query atp6.fasta -db watermelon.fsa
blastn -query atp8.fasta -db watermelon.fsa
blastn -query atp9.fasta -db watermelon.fsa
blastn -query ccmB.fasta -db watermelon.fsa
blastn -query ccmC.fasta -db watermelon.fsa
blastn -query ccmFc.fasta -db watermelon.fsa
blastn -query ccmFn.fasta -db watermelon.fsa
blastn -query cob.fasta -db watermelon.fsa
blastn -query cox1.fasta -db watermelon.fsa
blastn -query cox2.fasta -db watermelon.fsa
blastn -query cox3.fasta -db watermelon.fsa
blastn -query matR.fasta -db watermelon.fsa
blastn -query mttB.fasta -db watermelon.fsa
blastn -query nad1.fasta -db watermelon.fsa
blastn -query nad2.fasta -db watermelon.fsa
blastn -query nad3.fasta -db watermelon.fsa
blastn -query nad4.fasta -db watermelon.fsa
blastn -query nad4L.fasta -db watermelon.fsa
blastn -query nad5.fasta -db watermelon.fsa
blastn -query nad6.fasta -db watermelon.fsa
blastn -query nad7.fasta -db watermelon.fsa
blastn -query nad9.fasta -db watermelon.fsa
blastn -query rpl16.fasta -db watermelon.fsa
blastn -query rpl2.fasta -db watermelon.fsa
blastn -query rpl5.fasta -db watermelon.fsa
blastn -query rps1.fasta -db watermelon.fsa
blastn -query rps10.fasta -db watermelon.fsa
blastn -query rps12.fasta -db watermelon.fsa
blastn -query rps13.fasta -db watermelon.fsa
blastn -query rps19-1.fasta -db watermelon.fsa
blastn -query rps19-2.fasta -db watermelon.fsa
blastn -query rps3.fasta -db watermelon.fsa
blastn -query rps4.fasta -db watermelon.fsa
blastn -query rps7.fasta -db watermelon.fsa
blastn -query rrn18.fasta -db watermelon.fsa
blastn -query rrn26.fasta -db watermelon.fsa
blastn -query rrn5.fasta -db watermelon.fsa
blastn -query sdh3-1.fasta -db watermelon.fsa
blastn -query sdh3-2.fasta -db watermelon.fsa
blastn -query sdh4.fasta -db watermelon.fsa
blastn -query trnC(GCA)-1.fasta -db watermelon.fsa
blastn -query trnC(GCA)-2.fasta -db watermelon.fsa
blastn -query trnE(TTC).fasta -db watermelon.fsa
blastn -query trnF(GAA).fasta -db watermelon.fsa
blastn -query trnfM(CAT).fasta -db watermelon.fsa
blastn -query trnG(GCC)-1.fasta -db watermelon.fsa
blastn -query trnG(GCC)-2.fasta -db watermelon.fsa
blastn -query trnH(GTG)-cp.fasta -db watermelon.fsa
blastn -query trnI(CAT).fasta -db watermelon.fsa
blastn -query trnK(TTT).fasta -db watermelon.fsa
blastn -query trnM(CAT)-cp.fasta -db watermelon.fsa
blastn -query trnN(GTT)-cp.fasta -db watermelon.fsa
blastn -query trnP(TGG).fasta -db watermelon.fsa
blastn -query trnQ(TTG)-1.fasta -db watermelon.fsa
blastn -query trnQ(TTG)-2.fasta -db watermelon.fsa
blastn -query trnS(GCT).fasta -db watermelon.fsa
blastn -query trnS(TGA).fasta -db watermelon.fsa
blastn -query trnY(GTA).fasta -db watermelon.fsa
